### ISSUE TITLE
Plan - MVP

### ISSUE THREAD

**Issue by isithabib** [SchoolOfCode/escape-room-hackathon-room2grow#1]
Entry screen
Sprite finds "pot of gold"
End screen
```[tasklist]
### Tasks
- [x] Create algorithm
- [x] Entry screen with text description and an entry button
- [x] Clues in which order to click the sprites.
- [x] Create 7 book sprites that are different colours
- [x] Main room (Castle background?)/ look at sounds
- [x] Click sprites in order to make the treasure revealed
- [x] Click treasure (which will disappear) and then the door to escape
- [x] Display well done you got the treasre blah blah
```
